**Setup & Imports**

In [2]:
import pandas as pd
from pathlib import Path

# Configuration
DATA_FOLDER = Path("data")
OUTPUT_FILE = Path("airbnb_combined.csv")

**Processing & Merging Data**

In [3]:
csv_files = sorted(DATA_FOLDER.glob("*.csv"))

if not csv_files:
    print(f"Error: No CSV files found in {DATA_FOLDER.resolve()}")
else:
    all_dfs = []
    
    for file_path in csv_files:
        filename = file_path.stem.lower()
        
        # Extract metadata from filename
        if "weekdays" in filename:
            day_type = "weekday"
            city = filename.replace("_weekdays", "")
        elif "weekends" in filename:
            day_type = "weekend"
            city = filename.replace("_weekends", "")
        else:
            continue
            
        df = pd.read_csv(file_path)
        
        # Clean Unnamed columns
        df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
        
        # Add metadata columns
        df["city"] = city.capitalize()
        df["day_type"] = day_type
        
        all_dfs.append(df)
        print(f"Processed: {file_path.name} | Rows: {len(df)}")

    # Combine all dataframes
    combined_df = pd.concat(all_dfs, ignore_index=True, sort=False)
    print(f"\nTotal rows: {len(combined_df)}")

Processed: amsterdam_weekdays.csv | Rows: 1103
Processed: amsterdam_weekends.csv | Rows: 977
Processed: athens_weekdays.csv | Rows: 2653
Processed: athens_weekends.csv | Rows: 2627
Processed: barcelona_weekdays.csv | Rows: 1555
Processed: barcelona_weekends.csv | Rows: 1278
Processed: berlin_weekdays.csv | Rows: 1284
Processed: berlin_weekends.csv | Rows: 1200
Processed: budapest_weekdays.csv | Rows: 2074
Processed: budapest_weekends.csv | Rows: 1948
Processed: lisbon_weekdays.csv | Rows: 2857
Processed: lisbon_weekends.csv | Rows: 2906
Processed: london_weekdays.csv | Rows: 4614
Processed: london_weekends.csv | Rows: 5379
Processed: paris_weekdays.csv | Rows: 3130
Processed: paris_weekends.csv | Rows: 3558
Processed: rome_weekdays.csv | Rows: 4492
Processed: rome_weekends.csv | Rows: 4535
Processed: vienna_weekdays.csv | Rows: 1738
Processed: vienna_weekends.csv | Rows: 1799

Total rows: 51707

In [4]:
# Check row distribution
print("Row count by City and Day Type:")
print(combined_df.groupby(["city", "day_type"]).size())

# Export
combined_df.to_csv(OUTPUT_FILE, index=False)
print(f"\nSaved to: {OUTPUT_FILE.resolve()}")

Row count by City and Day Type:
city       day_type
Amsterdam  weekday     1103
           weekend      977
Athens     weekday     2653
           weekend     2627
Barcelona  weekday     1555
           weekend     1278
Berlin     weekday     1284
           weekend     1200
Budapest   weekday     2074
           weekend     1948
Lisbon     weekday     2857
           weekend     2906
London     weekday     4614
           weekend     5379
Paris      weekday     3130
           weekend     3558
Rome       weekday     4492
           weekend     4535
Vienna     weekday     1738
           weekend     1799
dtype: int64

Saved to: C:\Users\power\Desktop\intasks\airbnb_combined.csv

In [5]:
# Check number of columns
print(f"Total number of columns: {combined_df.shape[1]}")

# If you want to list all column names:
print("\nList of columns:")
print(list(combined_df.columns))

Total number of columns: 21

List of columns:
['realSum', 'room_type', 'room_shared', 'room_private', 'person_capacity', 'host_is_superhost', 'multi', 'biz', 'cleanliness_rating', 'guest_satisfaction_overall', 'bedrooms', 'dist', 'metro_dist', 'attr_index', 'attr_index_norm', 'rest_index', 'rest_index_norm', 'lng', 'lat', 'city', 'day_type']

In [ ]:
display(combined_df.head())

First 5 rows:

,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,...,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772,Amsterdam,weekday
1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,...,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432,Amsterdam,weekday
2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,...,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103,Amsterdam,weekday
3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,...,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663,Amsterdam,weekday
4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,...,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508,Amsterdam,weekday

Random sample of 5 rows:

,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
5107,149.509057,Entire home/apt,False,False,4.0,True,0,1,10.0,96.0,...,1.213226,0.227491,150.667689,5.676818,256.646260,3.832740,23.72589,37.98349,Athens,weekend
37666,272.625594,Private room,False,True,2.0,True,1,0,10.0,94.0,...,2.154104,0.173973,269.564224,13.107580,753.960484,34.781955,2.37850,48.86588,Paris,weekend
11307,191.408806,Private room,False,True,4.0,False,0,0,9.0,89.0,...,7.088638,2.300412,49.278277,7.513449,63.691456,13.132742,13.40129,52.58646,Berlin,weekday
38951,149.827570,Entire home/apt,False,False,2.0,False,0,0,10.0,96.0,...,2.858876,0.382180,245.072252,11.916656,600.695479,27.711483,2.37833,48.87597,Paris,weekend
25737,398.410123,Entire home/apt,False,False,4.0,False,0,1,9.0,80.0,...,2.569485,0.123896,455.150540,31.638019,1037.074907,18.569692,-0.12396,51.53131,London,weekday

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51707 entries, 0 to 51706
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   realSum                     51707 non-null  float64
 1   room_type                   51707 non-null  object
 2   room_shared                 51707 non-null  bool
 3   room_private                51707 non-null  bool
 4   person_capacity             51707 non-null  float64
 5   host_is_superhost           51707 non-null  bool
 6   multi                       51707 non-null  int64
 7   biz                         51707 non-null  int64
 8   cleanliness_rating          51707 non-null  float64
 9   guest_satisfaction_overall  51707 non-null  float64
 10  bedrooms                    51707 non-null  int64
 11  dist                        51707 non-null  float64
 12  metro_dist                  51707 non-null  float64
 13  attr_index                  51707 non-null  float64
 14  attr_index_norm             51707 non-null  float64
 15  rest_index                  51707 non-null  float64
 16  rest_index_norm             51707 non-null  float64
 17  lng                         51707 non-null  float64
 18  lat                         51707 non-null  float64
 19  city                        51707 non-null  object
 20  day_type                    51707 non-null  object
dtypes: bool(3), float64(12), int64(3), object(3)
memory usage: 7.2+ MB