In [26]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get("https://www.airbnb.com")

input("Press Enter...")

driver.quit()

In [27]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get("https://www.airbnb.com")

print(driver.title)

input("Press Enter...")

driver.quit()

Airbnb | Vacation rentals, cabins, beach houses, & more

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get("https://www.airbnb.com/s/Amsterdam--Netherlands/homes")

print(driver.current_url)
print(driver.title)

input("Press Enter...")
driver.quit()

https://www.airbnb.com/s/Amsterdam--Netherlands/homes
Airbnb | Amsterdam - Vacation Rentals & Places to Stay - North Holland

In [28]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get("https://www.airbnb.com/s/Amsterdam--Netherlands/homes")

time.sleep(10)

links = driver.find_elements(By.TAG_NAME, "a")

print("Total links:", len(links))

for link in links[:20]:
    print(link.get_attribute("href"))

driver.quit()

Total links: 251
https://www.airbnb.com/s/Amsterdam--Netherlands/homes#site-content
https://www.airbnb.com/
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783376510_P3ZAqDXx8ijEbzdY&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1123228325899462901?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3ck5CJvReByP0n5&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3hd2oUOThtrri0b&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3hd2oUOThtrri0b&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3hd2oUOThtrri0b&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783376513_P3hd2oUOThtrri0b&previous_page_section_name=1000&federated_search_id=6177c531-6733-4d9a-a880-c2839435a140

In [5]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get("https://www.airbnb.com/s/Amsterdam--Netherlands/homes")

time.sleep(10)

links = driver.find_elements(By.TAG_NAME, "a")

listing_urls = []

for link in links:

    href = link.get_attribute("href")

    if href and "/rooms/" in href:
        listing_urls.append(href)

listing_urls = list(set(listing_urls))

print(f"Total Listings: {len(listing_urls)}")

for url in listing_urls[:10]:
    print(url)

driver.quit()

Total Listings: 28
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783375011_P30wuzHhKIbS-rKN&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/1644186562669077207?search_mode=regular_search&adults=1&check_in=2026-07-06&check_out=2026-07-11&children=0&infants=0&pets=0&photo_id=2539845729&source_impression_id=p3_1783375012_P3Mh81k1foJOWXkA&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/1572471405121959061?search_mode=regular_search&adults=1&check_in=2026-07-06&check_out=2026-07-11&children=0&infants=0&pets=0&photo_id=2522878885&source_impression_id=p3_1783375012_P3BHU29-GijD0CZ3&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/834233?search_mode=regular_search&adults=1&category_tag=Tag%3A8678&check_in=2026-10-05&check_out=2026-10-10&children=0&infants=0&pets=0&photo_id=8099683&source_impression_id=p3_1783375011_P39yFluTp23wj7A1&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/957116576473186253?search_mode=regular_search&adults=1&check_in=2026-07-09&check_out=2026-07-14&children=0&infants=0&pets=0&source_impression_id=p3_1783375011_P3OXsNLI03AfxBPi&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/746060021045144380?search_mode=regular_search&adults=1&check_in=2026-07-07&check_out=2026-07-12&children=0&infants=0&pets=0&source_impression_id=p3_1783375011_P3fQs9bs3P85r8KP&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/1405580952002890361?search_mode=regular_search&adults=1&check_in=2026-07-06&check_out=2026-07-11&children=0&infants=0&pets=0&photo_id=2512806509&source_impression_id=p3_1783375012_P3o6y2u87-bjzyy_&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/1711524601006577597?search_mode=regular_search&adults=1&check_in=2026-07-06&check_out=2026-07-11&children=0&infants=0&pets=0&photo_id=2650122582&source_impression_id=p3_1783375012_P34yna8nz8Hcz7ui&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/1491976464258683042?search_mode=regular_search&adults=1&check_in=2026-07-06&check_out=2026-07-11&children=0&infants=0&pets=0&photo_id=2548344700&source_impression_id=p3_1783375012_P3vOcWOyZv4S8hUY&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041
https://www.airbnb.com/rooms/1572470556328153618?search_mode=regular_search&adults=1&check_in=2026-07-10&check_out=2026-07-15&children=0&infants=0&pets=0&photo_id=2564403840&source_impression_id=p3_1783375012_P3m4bQQ2gUpAmg4m&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041

In [29]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

url = listing_urls[0]

driver.get(url)

time.sleep(5)

print("TITLE:")
print(driver.title)

print("\nHEADERS:")
headers = driver.find_elements(By.TAG_NAME, "h1")

for h in headers:
    print(h.text)

driver.quit()

TITLE:
Waterfront studio apartment with beautiful windows - Apartments for Rent in Amsterdam, North Holland, Netherlands - Airbnb

HEADERS:

In [30]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

url = listing_urls[0]

driver.get(url)

time.sleep(10)

print("Original URL:")
print(url)

print("\nCurrent URL:")
print(driver.current_url)

print("\nTitle:")
print(driver.title)

input("Press Enter...")
driver.quit()

Original URL:
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783375011_P30wuzHhKIbS-rKN&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041

Current URL:
https://www.airbnb.com/rooms/1718851202796141005?search_mode=regular_search&adults=1&check_in=2026-08-07&check_out=2026-08-12&children=0&infants=0&pets=0&source_impression_id=p3_1783375011_P30wuzHhKIbS-rKN&previous_page_section_name=1000&federated_search_id=445e6583-ba4f-44f4-888c-ed31fd8a9041

Title:
Waterfront studio apartment with beautiful windows - Apartments for Rent in Amsterdam, North Holland, Netherlands - Airbnb

In [31]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get(listing_urls[0])

time.sleep(10)

print("=" * 100)
print("H1")
print("=" * 100)

for h in driver.find_elements(By.TAG_NAME, "h1"):
    print(h.text)

print("\n")
print("=" * 100)
print("H2")
print("=" * 100)

for h in driver.find_elements(By.TAG_NAME, "h2"):
    print(h.text)

print("\n")
print("=" * 100)
print("SPAN")
print("=" * 100)

spans = driver.find_elements(By.TAG_NAME, "span")

for s in spans[:100]:
    txt = s.text.strip()

    if txt:
        print(txt)

driver.quit()

====================================================================================================
H1
====================================================================================================
Waterfront studio apartment with beautiful windows


====================================================================================================
H2
====================================================================================================
Entire rental unit in Amsterdam, Netherlands
Listing highlights


====================================================================================================
SPAN
====================================================================================================
Start your search
Location
Check in / Check out
Guests
Show all photos
Show all photos
·
·
·
·
·
·
New listing
Start your morning right with the espresso machine.
Cosy apartment in the heart of Amsterdam's vibrant De Pijp. Enjoy beautiful sunset views over the iconic canals from the comfort of the living room. The open layout blends spaciousness with a warm, colour-rich interior. A metro station next door takes you to Dam Square in just 3 minutes. Fully equipped kitchen with an induction hob, oven, kettle and dishwasher. Start your day with barista-quality coffee from our Sage espresso machine before exploring the city.


Welcome to our colorful and cozy apartment in De Pijp, one of Amsterdam's most vibrant and beloved neighborhoods.

Located directly on the waterfront, the apartment is filled with natural light thanks to its impressive original 19th-century windows. Enjoy beautiful views over the canal while sipping your morning coffee or relaxing after a day exploring the city.

The apartment is perfect for couples, solo travelers, or friends looking for a comfortable and authentic Amsterdam experience. You'll be within walking distance of some of the city's best restaurants, cafés, boutique shops, museums, and the famous Albert Cuyp Market. The metro and tram are just a 3-minute walk away, making it easy to explore the rest of the city.

Sleeping Arrangements

The apartment is a spacious studio with a separate sleeping area. While the bedroom area doesn't have a door, it is set apart from the living space and provides a comfortable and private sleeping environment.

-Queen-size bed (160 cm) for 2 guests
-Additional guest can sleep on a floor matras (140 cm) or the couch (not a sleeping couch but you’re welcome to use it)
-Bedding and towels provided for all guests

Maximum 4 guests (2 guests are most comfortable).

Living Area

The living room is warm, colorful and full of character. Relax on the comfortable sofa while enjoying canal views through the large historic windows.

You'll also have access to:
-TV with streaming options
-Sonos speaker
-Dedicated workspace
-External monitor for remote working
-Dining table seating up to 6 guests

Kitchen

The fully equipped kitchen includes:

-Sage espresso machine for excellent coffee
-Dishwasher
-Oven
-Induction cooktop
-Kettle
-Toaster
-Cooking essentials

Perfect for both a quick breakfast and a home-cooked dinner.

Bathroom
- 1 bathroom
-Walk-in shower
-Toilet
-Towels provided

Location

Located in the heart of De Pijp, one of Amsterdam's most popular neighborhoods.

Within walking distance you'll find:
-Albert Cuyp Market
-Rijksmuseum
-Sarphatipark
-Excellent restaurants and cafés
-Boutique shopping streets

Some of our personal favorites:
-GlouGlou for natural wines
-Sjefietshe for dinner
-Lera for matcha and coffee

The metro and tram stop are only a 3-minute walk away, giving easy access to Amsterdam Central Station, the Zuidas business district, and Schiphol Airport.

Things to Know Before Booking

We want guests to know exactly what to expect and enjoy the authentic character of our home.

-The apartment is located on the second floor and accessed via two flights of traditional steep Amsterdam stairs.
-There is no elevator.
-The building dates back to the 19th century and has all the charm that comes with an older Amsterdam home, including a few imperfections.
-The curtains are not blackout curtains.
-As the apartment is located on a lively street, some traffic noise can be heard when the windows are open.
-During the day there can occasionally be some city noise even with the windows closed, but evenings and nights are generally quiet.
-Parking is available on the street, though finding a spot can be more difficult on weekends. Hi


0363 1571 D09C 5085 875A
Cosy apartment in the heart of Amsterdam's vibrant De Pijp. Enjoy beautiful sunset views over the iconic canals from the comfort of the living room. The open layout blends spaciousness with a warm, colour-rich interior. A metro station next door takes you to Dam Square in just 3 minutes. Fully equipped kitchen with an induction hob, oven, kettle and dishwasher. Start your day with barista-quality coffee from our Sage espresso machine before exploring the city.


Welcome to our colorful and cozy apartment in De Pijp, one of Amsterdam's most vibrant and beloved neighborhoods.

Located directly on the waterfront, the apartment is filled with natural light thanks to its impressive original 19th-century windows. Enjoy beautiful views over the canal while sipping your morning coffee or relaxing after a day exploring the city.

The apartment is perfect for couples, solo travelers, or friends looking for a comfortable and authentic Amsterdam experience. You'll be within walking distance of some of the city's best restaurants, cafés, boutique shops, museums, and the famous Albert Cuyp Market. The metro and tram are just a 3-minute walk away, making it easy to explore the rest of the city.

Sleeping Arrangements

The apartment is a spacious studio with a separate sleeping area. While the bedroom area doesn't have a door, it is set apart from the living space and provides a comfortable and private sleeping environment.

-Queen-size bed (160 cm) for 2 guests
-Additional guest can sleep on a floor matras (140 cm) or the couch (not a sleeping couch but you’re welcome to use it)
-Bedding and towels provided for all guests

Maximum 4 guests (2 guests are most comfortable).

Living Area

The living room is warm, colorful and full of character. Relax on the comfortable sofa while enjoying canal views through the large historic windows.

You'll also have access to:
-TV with streaming options
-Sonos speaker
-Dedicated workspace
-External monitor for remote working
-Dining table seating up to 6 guests

Kitchen

The fully equipped kitchen includes:

-Sage espresso machine for excellent coffee
-Dishwasher
-Oven
-Induction cooktop
-Kettle
-Toaster
-Cooking essentials

Perfect for both a quick breakfast and a home-cooked dinner.

Bathroom
- 1 bathroom
-Walk-in shower
-Toilet
-Towels provided

Location

Located in the heart of De Pijp, one of Amsterdam's most popular neighborhoods.

Within walking distance you'll find:
-Albert Cuyp Market
-Rijksmuseum
-Sarphatipark
-Excellent restaurants and cafés
-Boutique shopping streets

Some of our personal favorites:
-GlouGlou for natural wines
-Sjefietshe for dinner
-Lera for matcha and coffee

The metro and tram stop are only a 3-minute walk away, giving easy access to Amsterdam Central Station, the Zuidas business district, and Schiphol Airport.

Things to Know Before Booking

We want guests to know exactly what to expect and enjoy the authentic character of our home.

-The apartment is located on the second floor and accessed via two flights of traditional steep Amsterdam stairs.
-There is no elevator.
-The building dates back to the 19th century and has all the charm that comes with an older Amsterdam home, including a few imperfections.
-The curtains are not blackout curtains.
-As the apartment is located on a lively street, some traffic noise can be heard when the windows are open.
-During the day there can occasionally be some city noise even with the windows closed, but evenings and nights are generally quiet.
-Parking is available on the street, though finding a spot can be more difficult on weekends. Hi


0363 1571 D09C 5085 875A
Show more
P
r
i
c
e
s
i
n
c
l
u
d
e
a
l
l
f
e
e
s
Prices include all fees
ج.م 75,621
ج.م 62,222
Show price breakdown
 for 5 nights
ج.م 75,621
ج.م 62,222
Show price breakdown
 for 5 nights
ج.م 75,621
ج.م 62,222
Show price breakdown
 for 5 nights
ج.م 75,621
ج.م 62,222
Show price breakdown
ج.م 75,621
ج.م 75,621
ج.م 62,222
Show price breakdown
ج.م 62,222
Show price breakdown
for 5 nights
for 5 nights
1 guest
ج.م 0 today · Free cancellation before August 6

In [33]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

driver.get(listing_urls[0])

time.sleep(10)

property_name = driver.find_element(
    By.TAG_NAME,
    "h1"
).text

print(property_name)

Waterfront studio apartment with beautiful windows

In [34]:
spans = driver.find_elements(By.TAG_NAME, "span")

for s in spans:

    txt = s.text.strip()

    if "★" in txt:
        print(txt)

In [35]:
spans = driver.find_elements(By.TAG_NAME, "span")

for s in spans:

    txt = s.text.strip().lower()

    if "review" in txt:
        print(txt)

In [36]:
page_text = driver.page_source

if "superhost" in page_text.lower():
    print("Superhost Found")
else:
    print("Not Found")

Superhost Found

In [38]:
page_text = driver.page_source

if "guest favorite" in page_text.lower():
    print("Guest Favorite Found")
else:
    print("Not Found")

Not Found

In [39]:
body = driver.find_element(By.TAG_NAME, "body").text

for line in body.split('\n'):

    if "ج.م" in line:
        print(line)

In [40]:
spans = driver.find_elements(By.TAG_NAME, "span")

for i, s in enumerate(spans[:300]):
    txt = s.text.strip()

    if txt:
        print(i, "->", txt)

30 -> Start your search
31 -> Location
33 -> Check in / Check out
35 -> Guests

In [41]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install())
)

city = "Amsterdam"

url = f"https://www.airbnb.com/s/{city}--Netherlands/homes"

driver.get(url)

time.sleep(10)

links = driver.find_elements(By.TAG_NAME, "a")

listing_urls = []

for link in links:

    href = link.get_attribute("href")

    if href and "/rooms/" in href:
        listing_urls.append(href)

listing_urls = list(set(listing_urls))

print(f"Listings Found: {len(listing_urls)}")

for url in listing_urls[:5]:
    print(url)

Listings Found: 28
https://www.airbnb.com/rooms/33241583?search_mode=regular_search&adults=1&check_in=2026-07-21&check_out=2026-07-26&children=0&infants=0&pets=0&source_impression_id=p3_1783377115_P3Erkw3E2EatrCYN&previous_page_section_name=1000&federated_search_id=ee422dfb-4854-4ff6-8c98-4643a1f7991d
https://www.airbnb.com/rooms/1491976464258683042?search_mode=regular_search&adults=1&check_in=2026-07-14&check_out=2026-07-19&children=0&infants=0&pets=0&photo_id=2548344700&source_impression_id=p3_1783377117_P3N7U0N3rbUuQuCn&previous_page_section_name=1000&federated_search_id=ee422dfb-4854-4ff6-8c98-4643a1f7991d
https://www.airbnb.com/rooms/1503634899291650826?search_mode=regular_search&adults=1&check_in=2026-07-18&check_out=2026-07-23&children=0&infants=0&pets=0&source_impression_id=p3_1783377115_P3yilM9OF2DGKc6o&previous_page_section_name=1000&federated_search_id=ee422dfb-4854-4ff6-8c98-4643a1f7991d
https://www.airbnb.com/rooms/1572470556328153618?search_mode=regular_search&adults=1&check_in=2026-07-10&check_out=2026-07-15&children=0&infants=0&pets=0&photo_id=2564403840&source_impression_id=p3_1783377117_P3gb_8y29ggZfmsi&previous_page_section_name=1000&federated_search_id=ee422dfb-4854-4ff6-8c98-4643a1f7991d
https://www.airbnb.com/rooms/1718896659013342707?search_mode=regular_search&adults=1&check_in=2026-07-28&check_out=2026-08-02&children=0&infants=0&pets=0&source_impression_id=p3_1783377115_P3n6KrqDYkTTosgs&previous_page_section_name=1000&federated_search_id=ee422dfb-4854-4ff6-8c98-4643a1f7991d

In [42]:
url = listing_urls[0]

driver.get(url)

time.sleep(8)

property_name = driver.find_element(
    By.TAG_NAME,
    "h1"
).text

print(property_name)

3-Bedroom Apartment - ID Aparthotel

In [43]:
record = {
    "property_name": property_name,
    "url": url
}

print(record)

{'property_name': '3-Bedroom Apartment - ID Aparthotel', 'url': 'https://www.airbnb.com/rooms/33241583?search_mode=regular_search&adults=1&check_in=2026-07-21&check_out=2026-07-26&children=0&infants=0&pets=0&source_impression_id=p3_1783377115_P3Erkw3E2EatrCYN&previous_page_section_name=1000&federated_search_id=ee422dfb-4854-4ff6-8c98-4643a1f7991d'}

In [44]:
data = []

for url in listing_urls[:5]:

    try:

        driver.get(url)

        time.sleep(5)

        property_name = driver.find_element(
            By.TAG_NAME,
            "h1"
        ).text

        data.append({
            'property_name': property_name,
            'url': url
        })

        print(property_name)

    except Exception as e:

        print("Error:", e)

3-Bedroom Apartment - ID Aparthotel
The Social Hub Amsterdam West 3*
Zenstay Hotel Amsterdam - Zaandam | Retreat Suite
Conscious Hotel Vondelpark
Charming 1BDR in local area

In [45]:
import pandas as pd

scraped_df = pd.DataFrame(data)

scraped_df.head()

,property_name,url
0,3-Bedroom Apartment - ID Aparthotel,https://www.airbnb.com/rooms/33241583?search_m...
1,The Social Hub Amsterdam West 3*,https://www.airbnb.com/rooms/14919764642586830...
2,Zenstay Hotel Amsterdam - Zaandam | Retreat Suite,https://www.airbnb.com/rooms/15036348992916508...
3,Conscious Hotel Vondelpark,https://www.airbnb.com/rooms/15724705563281536...
4,Charming 1BDR in local area,https://www.airbnb.com/rooms/17188966590133427...

In [46]:
data.append({
    'city': 'Amsterdam',
    'property_name': property_name,
    'url': url
})

In [47]:
page_text = driver.page_source.lower()

superhost = "superhost" in page_text

print(superhost)

True

In [48]:
data.append({
    'city': 'Amsterdam',
    'property_name': property_name,
    'superhost': superhost,
    'url': url
})

In [49]:
property_type = driver.find_element(
    By.TAG_NAME,
    'h2'
).text

In [50]:
data.append({
    'city': 'Amsterdam',
    'property_name': property_name,
    'property_type': property_type,
    'superhost': superhost,
    'url': url
})

In [51]:
from selenium.webdriver.common.by import By
import time

def get_listing_urls(driver, city):

    search_url = f"https://www.airbnb.com/s/{city}/homes"

    driver.get(search_url)

    time.sleep(10)

    links = driver.find_elements(By.TAG_NAME, "a")

    listing_urls = []

    for link in links:

        href = link.get_attribute("href")

        if href and "/rooms/" in href:
            listing_urls.append(href)

    return list(set(listing_urls))

In [52]:
def scrape_listing(driver, url, city):

    try:

        driver.get(url)

        time.sleep(5)

        property_name = driver.find_element(
            By.TAG_NAME,
            "h1"
        ).text

        property_type = driver.find_element(
            By.TAG_NAME,
            "h2"
        ).text

        page_text = driver.page_source.lower()

        superhost = "superhost" in page_text

        return {
            "city": city,
            "property_name": property_name,
            "property_type": property_type,
            "superhost": superhost,
            "url": url
        }

    except Exception as e:

        print(f"Error: {url}")

        return None

In [53]:
city = "Amsterdam"

listing_urls = get_listing_urls(driver, city)

row = scrape_listing(
    driver,
    listing_urls[0],
    city
)

print(row)

{'city': 'Amsterdam', 'property_name': 'Lovely Apartment with Parking', 'property_type': 'Entire rental unit in Amsterdam, Netherlands', 'superhost': True, 'url': 'https://www.airbnb.com/rooms/1722717549067251657?search_mode=regular_search&adults=1&check_in=2026-07-19&check_out=2026-07-24&children=0&infants=0&pets=0&source_impression_id=p3_1783377744_P3fFidOON_MEVmP-&previous_page_section_name=1000&federated_search_id=ee65e359-c50c-4bdc-b971-e35c40131553'}

In [54]:
data = []

for url in listing_urls[:10]:

    row = scrape_listing(
        driver,
        url,
        city
    )

    if row:
        data.append(row)

Error: https://www.airbnb.com/rooms/1717293919151945166?search_mode=regular_search&adults=1&check_in=2026-07-07&check_out=2026-07-12&children=0&infants=0&pets=0&source_impression_id=p3_1783377745_P3EjF6HLKbveR3bp&previous_page_section_name=1000&federated_search_id=ee65e359-c50c-4bdc-b971-e35c40131553
Error: https://www.airbnb.com/rooms/1095467564153718913?search_mode=regular_search&adults=1&check_in=2026-07-07&check_out=2026-07-12&children=0&infants=0&pets=0&photo_id=2512806794&source_impression_id=p3_1783377746_P3cyPYa94AxcBkLl&previous_page_section_name=1000&federated_search_id=ee65e359-c50c-4bdc-b971-e35c40131553
Error: https://www.airbnb.com/rooms/30762441?search_mode=regular_search&adults=1&check_in=2026-08-13&check_out=2026-08-18&children=0&infants=0&pets=0&source_impression_id=p3_1783377745_P3lA02sQKkq12zIv&previous_page_section_name=1000&federated_search_id=ee65e359-c50c-4bdc-b971-e35c40131553

In [55]:
import pandas as pd

scraped_df = pd.DataFrame(data)

scraped_df.head()

,city,property_name,property_type,superhost,url
0,Amsterdam,Lovely Apartment with Parking,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17227175490672516...
1,Amsterdam,Cityden | 2-Bedroom Apartment + Bath | Aparthotel,"Entire serviced apartment in Amstelveen, Nethe...",True,https://www.airbnb.com/rooms/33092943?search_m...
2,Amsterdam,Maxhotel Amsterdam Schiphol Airport,"Hotel in Hoofddorp, Netherlands",True,https://www.airbnb.com/rooms/12186368942501312...
3,Amsterdam,Elegant waterfront maisonette in Amsterdam,,True,https://www.airbnb.com/rooms/17215594937038424...
4,Amsterdam,Waterfront studio apartment with beautiful win...,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17188512027961410...

In [62]:
cities = [
    "Amsterdam",
    "Athens"
]

all_data = []

for city in cities:

    print("=" * 60)
    print(f"Scraping {city}")

    urls = get_listing_urls(
        driver,
        city
    )

    print(f"Listings Found: {len(urls)}")

    for i, url in enumerate(urls, start=1):

        print(f"Listing {i}")

        row = scrape_listing(
            driver,
            url,
            city
        )

        if row:
            all_data.append(row)
            

    print(f"Total Records Collected: {len(all_data)}")

============================================================
Scraping Amsterdam
Listings Found: 18
Listing 1
Listing 2
Listing 3
Listing 4
Listing 5
Listing 6
Listing 7
Listing 8
Listing 9
Listing 10
Listing 11
Listing 12
Listing 13
Listing 14
Listing 15
Listing 16
Listing 17
Listing 18
Total Records Collected: 18
============================================================
Scraping Athens
Listings Found: 18
Listing 1
Listing 2
Listing 3
Listing 4
Listing 5
Listing 6
Listing 7
Listing 8
Listing 9
Listing 10
Listing 11
Listing 12
Listing 13
Listing 14
Error: https://www.airbnb.com/rooms/1721580213862064304?search_mode=regular_search&adults=1&check_in=2026-07-15&check_out=2026-07-20&children=0&infants=0&pets=0&source_impression_id=p3_1783378924_P3mCxaGYLhix5Qx7&previous_page_section_name=1000&federated_search_id=60d58e85-8c47-4bf4-b2b7-9ce958affb02
Listing 15
Listing 16
Listing 17
Listing 18
Error: https://www.airbnb.com/rooms/628473879447208738?search_mode=regular_search&adults=1&check_in=2026-07-13&check_out=2026-07-18&children=0&infants=0&pets=0&source_impression_id=p3_1783378924_P37-VJ59mA9ciZrV&previous_page_section_name=1000&federated_search_id=60d58e85-8c47-4bf4-b2b7-9ce958affb02
Total Records Collected: 34

In [ ]:
import pandas as pd

scraped_df = pd.DataFrame(all_data)

scraped_df.head(34)

,city,property_name,property_type,superhost,url
0,Amsterdam,NEW: Spacious 3BR family friendly +FREE Parking,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17089307162104038...
1,Amsterdam,2-Bedroom Apartment - ID Aparthotel,,True,https://www.airbnb.com/rooms/33241384?search_m...
2,Amsterdam,Elegant waterfront maisonette in Amsterdam,"Entire condo in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17215594937038424...
3,Amsterdam,Numa | Large Accessible 2 Bedroom Apartment,"Entire serviced apartment in Amsterdam, Nether...",True,https://www.airbnb.com/rooms/11275100418527698...
4,Amsterdam,Stylish Serviced Apartment near Central Station,,True,https://www.airbnb.com/rooms/30762441?search_m...
5,Amsterdam,3-Bedroom Apartment - ID Aparthotel,,True,https://www.airbnb.com/rooms/33241583?search_m...
6,Amsterdam,Cityden | 2-Bedroom Apartment + Bath | Aparthotel,"Entire serviced apartment in Amstelveen, Nethe...",True,https://www.airbnb.com/rooms/33092943?search_m...
7,Amsterdam,4-Bedroom Apartment - ID Aparthotel,,True,https://www.airbnb.com/rooms/33242539?search_m...
8,Amsterdam,2-Bedroom Apartment | The July - Boat & Co,"Entire serviced apartment in Amsterdam, Nether...",True,https://www.airbnb.com/rooms/38170899?search_m...
9,Amsterdam,Lovely Apartment with Parking,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17227175490672516...
10,Amsterdam,LoftSolitudo. studio (2nd floor) for max. 3 pe...,,True,https://www.airbnb.com/rooms/17172939191519451...
11,Amsterdam,Zenstay Hotel Amsterdam - Zaandam | Retreat Suite,"Room in hotel in Zaandam, Netherlands",True,https://www.airbnb.com/rooms/15036348992916508...
12,Amsterdam,Spacious Waterfront Apartment in City Center,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/16594521733615788...
13,Amsterdam,Spacious Serviced Apartment with River View,"Entire serviced apartment in Amsterdam, Nether...",True,https://www.airbnb.com/rooms/42446371?search_m...
14,Amsterdam,"Numa | Studio w/ Kitchen, Sofa Bed & Extra Bed","Entire serviced apartment in Amsterdam, Nether...",True,https://www.airbnb.com/rooms/16296664877767230...
15,Amsterdam,Charming 1BDR in local area,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17188966590133427...
16,Amsterdam,Design Studio for 4: Peaceful spot,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/90567627903213654...
17,Amsterdam,Waterfront studio apartment with beautiful win...,"Entire rental unit in Amsterdam, Netherlands",True,https://www.airbnb.com/rooms/17188512027961410...
18,Athens,1930s Architect-Designed Gem | 3BR 110m² Athens,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/17070383685257470...
19,Athens,Ivory Lux Home • Walk to Acropolis,,True,https://www.airbnb.com/rooms/16879613561267999...
20,Athens,Luxury Apartment in heart of Athens-Blue Graphite,"Entire condo in Athens, Greece",True,https://www.airbnb.com/rooms/10165895789719919...
21,Athens,"""Seven Hills"" Luxury Residence with Rooftop Patio","Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/10208051377805430...
22,Athens,The Athens Micro Loft with private jacuzzi,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/17137510288171436...
23,Athens,*Spotless Sanctuary* - *Fully Renovated June ‘26*,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/17033864478682546...
24,Athens,Modern Industrial Loft 3 - ! Just Renovated !,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/17034182097735239...
25,Athens,Art Base Studio | Premium,,True,https://www.airbnb.com/rooms/17060196676516579...
26,Athens,Echoes of Athens - Hidden Gem Steps from Acrop...,"Entire condo in Athens, Greece",True,https://www.airbnb.com/rooms/16929206678080278...
27,Athens,Emerald 2 BDs Apartment with Balcony in Exarcheia,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/16383631602864535...
28,Athens,Acropolis Eclectic Residence II,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/16761466039180876...
29,Athens,Bright & Luxurious 3BR Suite | Metro | By Museum,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/16702912704508629...
30,Athens,Modern Industrial Loft 1 - ! Just Renovated !,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/17035894006702667...
31,Athens,Sozo72 · Jacuzzi · 2BR · metro 3 min · sleeps 6,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/17028718401545216...
32,Athens,Victoria Urban Retreat,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/16811542929787488...
33,Athens,Filoksenia Apartments Athens City Centre,"Entire rental unit in Athens, Greece",True,https://www.airbnb.com/rooms/16980379885587762...

In [66]:
from selenium.webdriver.common.by import By
import time

def get_listing_urls(driver, city, target=50):

    search_url = f"https://www.airbnb.com/s/{city}/homes"

    driver.get(search_url)

    time.sleep(8)

    urls = set()

    last_count = 0

    for _ in range(20):

        links = driver.find_elements(By.TAG_NAME, "a")

        for link in links:

            href = link.get_attribute("href")

            if href and "/rooms/" in href:
                urls.add(href)

        print(f"Collected: {len(urls)}")

        if len(urls) >= target:
            break

        driver.execute_script(
            "window.scrollTo(0, document.body.scrollHeight);"
        )

        time.sleep(4)

        if len(urls) == last_count:
            break

        last_count = len(urls)

    return list(urls)[:target]

In [67]:
urls = get_listing_urls(
    driver,
    "Amsterdam",
    target=50
)

print(len(urls))

Collected: 28
Collected: 28
28

In [68]:
buttons = driver.find_elements(By.TAG_NAME, "button")

for b in buttons:
    txt = b.text.strip()

    if txt:
        print(txt)

Location
Check in / Check out
Guests
Filters
Kitchen
Allows pets
Instant Book
Washer
Air conditioning
Free parking
Guest favorite
Wifi
1+ bathrooms
Self check-in
ج.م 31,092
ج.م 31,092 for 5 nights
ج.م 24,075
ج.م 24,075 for 5 nights
ج.م 32,273
ج.م 32,273 for 5 nights, originally ج.م 38,422
ج.م 38,155
ج.م 38,155 for 5 nights
ج.م 39,482
ج.م 39,482 for 5 nights
ج.م 42,470
ج.م 42,470 for 5 nights
ج.م 37,676
ج.م 37,676 for 5 nights
ج.م 71,294
ج.م 71,294 for 5 nights
ج.م 31,428
ج.م 31,428 for 5 nights
ج.م 46,834
ج.م 46,834 for 5 nights
1
English (US)
EGP

In [69]:
print(driver.current_url)

https://www.airbnb.com/s/Amsterdam/homes

In [70]:
driver.get(urls[0])
time.sleep(10)

In [71]:
body = driver.find_element(By.TAG_NAME, "body").text

print(body[:5000])

Skip to content
Start your search
Location
Anywhere
Check in / Check out
Anytime
Guests
Add guests
Postillion Hotel Amsterdam
Share
Save
Show all photos
Translation on
This symbol shows when content from Hosts and guests has been automatically translated. Change this setting at any time.
Translation settings

In [72]:
for line in body.split("\n"):

    if "review" in line.lower():
        print(line)

In [73]:
for line in body.split("\n"):

    if "guest" in line.lower():
        print(line)

Guests
Add guests
This symbol shows when content from Hosts and guests has been automatically translated. Change this setting at any time.

In [74]:
driver.get(url)
time.sleep(10)

In [75]:
body = driver.find_element(By.TAG_NAME, "body").text

for line in body.split("\n"):

    if "review" in line.lower():
        print(line)

123 reviews
Reviews
Rated 4.97 out of 5 from 123 reviews.
This home is in the top 5% of eligible listings based on ratings, reviews, and reliability
Show all 123 reviews
How reviews work
How reviews work

In [76]:
body = driver.find_element(By.TAG_NAME, "body").text

for line in body.split("\n"):

    if "guest favorite" in line.lower():
        print(line)

Guest favorite

In [77]:
import re

body = driver.find_element(By.TAG_NAME, "body").text

ratings = re.findall(r"\b[0-5]\.\d+\b", body)

print(ratings[:20])

['4.97', '4.97', '4.97', '4.97']

In [82]:
from selenium.webdriver.common.by import By
import time

def get_listing_urls(driver, city):

    search_url = f"https://www.airbnb.com/s/{city}/homes"

    driver.get(search_url)

    time.sleep(10)

    urls = set()

    links = driver.find_elements(By.TAG_NAME, "a")

    for link in links:

        href = link.get_attribute("href")

        if href and "/rooms/" in href:
            urls.add(href)

    return list(urls)

In [83]:
import re
import time

def scrape_listing(driver, url, city):

    try:

        driver.get(url)

        time.sleep(8)

        body = driver.find_element(
            By.TAG_NAME,
            "body"
        ).text

        property_name = driver.find_element(
            By.TAG_NAME,
            "h1"
        ).text

        h2_tags = driver.find_elements(
            By.TAG_NAME,
            "h2"
        )

        property_type = (
            h2_tags[0].text
            if len(h2_tags) > 0
            else None
        )

        superhost = (
            "superhost" in body.lower()
        )

        guest_favorite = (
            "guest favorite" in body.lower()
        )

        ratings = re.findall(
            r"\b[0-5]\.\d+\b",
            body
        )

        rating = (
            float(ratings[0])
            if ratings
            else None
        )

        review_match = re.search(
            r"(\d+)\s+reviews",
            body,
            re.IGNORECASE
        )

        reviews_count = (
            int(review_match.group(1))
            if review_match
            else None
        )

        return {
            "city": city,
            "property_name": property_name,
            "property_type": property_type,
            "rating": rating,
            "reviews_count": reviews_count,
            "superhost": superhost,
            "guest_favorite": guest_favorite,
            "url": url
        }

    except Exception as e:

        print(f"Error: {url}")

        return None

In [ ]:
import pandas as pd
import random

cities = [
    'amsterdam',
    'athens',
    'barcelona',
    'berlin',
    'budapest',
    'lisbon',
    'paris',
    'rome',
    'vienna',
    'london'
]

all_data = []

for city in cities:

    print("=" * 60)
    print(f"Scraping {city}")

    urls = get_listing_urls(
        driver,
        city
    )

    print(f"Found {len(urls)} Listings")

    # ناخد أول 30 عقار
    urls = urls[:30]

    for i, url in enumerate(urls, start=1):

        print(f"{city} | Listing {i}")

        row = scrape_listing(
            driver,
            url,
            city
        )

        if row:
            all_data.append(row)

        time.sleep(
            random.uniform(2, 5)
        )

============================================================
Scraping Amsterdam
Found 28 Listings
Amsterdam | Listing 1
Amsterdam | Listing 2
Amsterdam | Listing 3
Amsterdam | Listing 4
Amsterdam | Listing 5
Amsterdam | Listing 6
Amsterdam | Listing 7
Amsterdam | Listing 8
Amsterdam | Listing 9
Amsterdam | Listing 10
Amsterdam | Listing 11
Amsterdam | Listing 12
Amsterdam | Listing 13
Amsterdam | Listing 14
Amsterdam | Listing 15
Amsterdam | Listing 16
Amsterdam | Listing 17
Amsterdam | Listing 18
Amsterdam | Listing 19
Amsterdam | Listing 20
Amsterdam | Listing 21
Amsterdam | Listing 22
Amsterdam | Listing 23
Amsterdam | Listing 24
Amsterdam | Listing 25
Amsterdam | Listing 26
Amsterdam | Listing 27
Amsterdam | Listing 28
============================================================
Scraping Athens
Found 18 Listings
Athens | Listing 1
Athens | Listing 2
Athens | Listing 3
Athens | Listing 4
Athens | Listing 5
Athens | Listing 6
Athens | Listing 7
Athens | Listing 8
Athens | Listing 9
Athens | Listing 10
Athens | Listing 11
Athens | Listing 12
Athens | Listing 13
Athens | Listing 14
Athens | Listing 15
Athens | Listing 16
Athens | Listing 17
Athens | Listing 18

In [85]:
scraped_df = pd.DataFrame(all_data)
scraped_df

,city,property_name,property_type,rating,reviews_count,superhost,guest_favorite,url
0,Amsterdam,Lovely Apartment with Parking,"Entire rental unit in Amsterdam, Netherlands",4.78,NaN,False,False,https://www.airbnb.com/rooms/17227175490672516...
1,Amsterdam,2-Bedroom Apartment - ID Aparthotel,"Entire serviced apartment in Amsterdam, Nether...",4.78,882.0,True,False,https://www.airbnb.com/rooms/33241384?search_m...
2,Amsterdam,Maxhotel Amsterdam Schiphol Airport,"Hotel in Hoofddorp, Netherlands",4.68,660.0,False,False,https://www.airbnb.com/rooms/12186368942501312...
3,Amsterdam,LoftSolitudo. studio (2nd floor) for max. 3 pe...,"Entire loft in Amsterdam, Netherlands",4.78,NaN,False,False,https://www.airbnb.com/rooms/17172939191519451...
4,Amsterdam,Postillion Hotel Amsterdam,"Hotel in Amsterdam, Netherlands",4.74,437.0,False,False,https://www.airbnb.com/rooms/14055809520028903...
5,Amsterdam,The Social Hub Amsterdam West 3*,"Hotel in Amsterdam, Netherlands",4.64,277.0,False,False,https://www.airbnb.com/rooms/14919764642586830...
6,Amsterdam,"Max Brown Hotel Museum Square, Sircle Collection","Hotel in Amsterdam, Netherlands",4.65,824.0,False,False,https://www.airbnb.com/rooms/10954675641537189...
7,Amsterdam,3-Bedroom Apartment - ID Aparthotel,"Entire serviced apartment in Amsterdam, Nether...",4.77,319.0,True,False,https://www.airbnb.com/rooms/33241583?search_m...
8,Amsterdam,Hostel The Veteran,"Hotel in Amsterdam, Netherlands",5.00,4.0,False,False,https://www.airbnb.com/rooms/17115246010065775...
9,Amsterdam,Charming 1BDR in local area,"Entire rental unit in Amsterdam, Netherlands",4.88,95.0,False,False,https://www.airbnb.com/rooms/17188966590133427...
10,Amsterdam,Hotel V Oosterpark by Conscious,"Hotel in Amsterdam, Netherlands",4.87,135.0,False,False,https://www.airbnb.com/rooms/15724823394767423...
11,Amsterdam,Volkshotel Amsterdam,"Hotel in Amsterdam, Netherlands",4.80,561.0,False,False,https://www.airbnb.com/rooms/16441865626690772...
12,Amsterdam,Design Studio for 4: Peaceful spot,"Entire rental unit in Amsterdam, Netherlands",4.77,430.0,True,False,https://www.airbnb.com/rooms/90567627903213654...
13,Amsterdam,NEW: Spacious 3BR family friendly +FREE Parking,"Entire rental unit in Amsterdam, Netherlands",1.50,NaN,False,False,https://www.airbnb.com/rooms/17089307162104038...
14,Amsterdam,Cityden | 2-Bedroom Apartment + Bath | Aparthotel,"Entire serviced apartment in Amstelveen, Nethe...",4.77,770.0,True,False,https://www.airbnb.com/rooms/33092943?search_m...
15,Amsterdam,Conscious Hotel The Tire Station,"Hotel in Amsterdam, Netherlands",4.74,242.0,False,False,https://www.airbnb.com/rooms/15724714051219590...
16,Amsterdam,Spacious Serviced Apartment with River View,"Entire serviced apartment in Amsterdam, Nether...",4.84,729.0,True,True,https://www.airbnb.com/rooms/42446371?search_m...
17,Amsterdam,Spacious Waterfront Apartment in City Center,"Entire rental unit in Amsterdam, Netherlands",4.94,17.0,False,True,https://www.airbnb.com/rooms/16594521733615788...
18,Amsterdam,Zenstay Hotel Amsterdam - Zaandam | Retreat Suite,"Room in hotel in Zaandam, Netherlands",5.00,12.0,False,True,https://www.airbnb.com/rooms/15036348992916508...
19,Amsterdam,"Numa | Studio w/ Kitchen, Sofa Bed & Extra Bed","Entire serviced apartment in Amsterdam, Nether...",4.86,7.0,False,False,https://www.airbnb.com/rooms/16296664877767230...
20,Amsterdam,Waterfront studio apartment with beautiful win...,"Entire rental unit in Amsterdam, Netherlands",5.00,NaN,False,False,https://www.airbnb.com/rooms/17188512027961410...
21,Amsterdam,Urban Lodge Hotel,"Hotel in Amsterdam, Netherlands",4.73,170.0,False,False,https://www.airbnb.com/rooms/11425502308110225...
22,Amsterdam,4-Bedroom Apartment - ID Aparthotel,"Entire serviced apartment in Amsterdam, Nether...",2.50,130.0,True,True,https://www.airbnb.com/rooms/33242539?search_m...
23,Amsterdam,2-Bedroom Apartment | The July - Boat & Co,"Entire serviced apartment in Amsterdam, Nether...",4.95,37.0,True,True,https://www.airbnb.com/rooms/38170899?search_m...
24,Amsterdam,Conscious Hotel Vondelpark,"Hotel in Amsterdam, Netherlands",4.73,842.0,False,False,https://www.airbnb.com/rooms/15724705563281536...
25,Amsterdam,Elegant waterfront maisonette in Amsterdam,"Entire condo in Amsterdam, Netherlands",4.78,NaN,False,False,https://www.airbnb.com/rooms/17215594937038424...
26,Amsterdam,Stylish Serviced Apartment near Central Station,"Entire serviced apartment in Amsterdam, Nether...",4.81,717.0,True,False,https://www.airbnb.com/rooms/30762441?search_m...
27,Amsterdam,Numa | Large Accessible 2 Bedroom Apartment,"Entire serviced apartment in Amsterdam, Nether...",4.77,22.0,False,False,https://www.airbnb.com/rooms/11275100418527698...
28,Athens,Modern Industrial Loft 1 - ! Just Renovated !,"Entire rental unit in Athens, Greece",5.00,4.0,True,False,https://www.airbnb.com/rooms/17035894006702667...
29,Athens,Emerald 2 BDs Apartment with Balcony in Exarcheia,"Entire rental unit in Athens, Greece",5.00,23.0,True,True,https://www.airbnb.com/rooms/16383631602864535...
30,Athens,Classy & Lux Apartment in Athens,"Entire rental unit in Athens, Greece",2.80,NaN,False,False,https://www.airbnb.com/rooms/17215802138620643...
31,Athens,Sozo72 · Jacuzzi · 2BR · metro 3 min · sleeps 6,"Entire rental unit in Athens, Greece",4.81,3.0,True,False,https://www.airbnb.com/rooms/17028718401545216...
32,Athens,*Spotless Sanctuary* - *Fully Renovated June ‘26*,"Entire rental unit in Athens, Greece",5.00,6.0,True,True,https://www.airbnb.com/rooms/17033864478682546...
33,Athens,Filoksenia Apartments Athens City Centre,"Entire rental unit in Athens, Greece",5.00,3.0,False,False,https://www.airbnb.com/rooms/16980379885587762...
34,Athens,Victoria Urban Retreat,"Entire rental unit in Athens, Greece",5.00,2.0,False,False,https://www.airbnb.com/rooms/16811542929787488...
35,Athens,Luxury Apartment in heart of Athens-Blue Graphite,"Entire condo in Athens, Greece",2.50,118.0,True,True,https://www.airbnb.com/rooms/10165895789719919...
36,Athens,Echoes of Athens - Hidden Gem Steps from Acrop...,"Entire condo in Athens, Greece",5.00,2.0,False,False,https://www.airbnb.com/rooms/16929206678080278...
37,Athens,Ivory Lux Home • Walk to Acropolis,"Entire rental unit in Athens, Greece",5.00,8.0,True,True,https://www.airbnb.com/rooms/16879613561267999...
38,Athens,Art Base Studio | Premium,"Entire condo in Athens, Greece",4.84,2.0,False,False,https://www.airbnb.com/rooms/17060196676516579...
39,Athens,"Guest House Studio - Private Bathroom, kitchen...","Entire guesthouse in Athens, Greece",4.97,123.0,True,True,https://www.airbnb.com/rooms/62847387944720873...
40,Athens,"""Seven Hills"" Luxury Residence with Rooftop Patio","Entire rental unit in Athens, Greece",4.89,73.0,False,True,https://www.airbnb.com/rooms/10208051377805430...
41,Athens,Acropolis Eclectic Residence II,"Entire rental unit in Athens, Greece",5.00,3.0,True,False,https://www.airbnb.com/rooms/16761466039180876...
42,Athens,Bright & Luxurious 3BR Suite | Metro | By Museum,"Entire rental unit in Athens, Greece",5.00,5.0,False,True,https://www.airbnb.com/rooms/16702912704508629...
43,Athens,Thissio Luxury open-plan loft,"Entire home in Athens, Greece",5.00,3.0,False,False,https://www.airbnb.com/rooms/16744408406941566...
44,Athens,1930s Architect-Designed Gem | 3BR 110m² Athens,"Entire rental unit in Athens, Greece",4.63,3.0,False,False,https://www.airbnb.com/rooms/17070383685257470...
45,Athens,The Athens Micro Loft with private jacuzzi,"Entire rental unit in Athens, Greece",4.81,3.0,True,False,https://www.airbnb.com/rooms/17137510288171436...

In [86]:
scraped_df.shape

(46, 8)